### PR TITLE
Reduce default run time for rb\_tree benchmark to 10 minutes

### LINKED ISSUE #41: Reduce scope of `rb_bench`
The default should be something that is runnable within ~10minutes preferably less.

cc: @kpamnany

### PR DESCRIPTION
**Pull request by kpamnany**
Closes #41.

### CODE REVIEW

**Comment by oscardssmith** [comment]
I don't love gating based on time since that will make results not comparable between different versions of Julia. Not sure what the right answer is though.

**Comment by d-netto** [comment]
From what I understood, the purpose of this benchmark is to illustrate poor cache utilization on marking.

If the same behavior happens with a smaller tree, then perhaps it could be better to reduce the size of the data structure rather than putting a time cutoff.

**Comment by kpamnany** [comment]
The purpose of the benchmark is to show how long GC pauses can get when the live heap is a large pointer graph. You would compare it with another version visually, with a plot of pause times so the number of iterations doesn't need to be identical.

**Comment by d-netto** [comment]
Those are correlated in the end...

> with a plot of pause times so the number of iterations doesn't need to be identical.

Minor detail: if the number of iterations is not the same, then I think the tables reported at the very end could be misleading: I think #iters being different by one could cause a significant difference in mark-times, for example. 

From what you are proposing, I think it would make sense to run the benchmark only once by default and just report the time iteration by iteration.

Again, a minor detail: comparing pause times iteration by iteration seems reasonable to me.

**Comment by kpamnany** [comment]
> Minor detail: if the number of iterations is not the same, then I think the tables reported at the very end could be misleading: I think #iters being different by one could cause a significant difference in mark-times, for example.

Yes, the table at the end is not especially meaningful for this benchmark.

> From what you are proposing, I think it would make sense to run the benchmark only once by default and just report the time iteration by iteration.

That's how I run it (`julia --project run_benchmarks.jl slow rb_tree -n1`), and the output of the run is a series of `@timev`s, one for every million iterations of the loop.

**Comment by d-netto** [comment]
bump?

**Pull request merged**
