### PR TITLE
counting cycles in GC

### PR DESCRIPTION
**Pull request by d-netto**
Instrumentation to count cycles in GC: basically wraps a `perf_event_open` syscall in the GC callbacks.

TODO:
- [x] Add script to compile `measure_gc_cyles.c` into a shared library.
- [ ] Further testing.

### CODE REVIEW

**Comment by d-netto** [comment]
Example of output table:

```
┌─────────┬────────────┬─────────┬──────────────┬───────────┬────────────┬──────────────┬───────────────────┬──────────┬────────────┐
│         │ total time │ gc time │ cycles in gc │ mark time │ sweep time │ max GC pause │ time to safepoint │ max heap │ percent gc │
│         │         ms │      ms │          1e6 │        ms │         ms │           ms │                us │       MB │          % │
├─────────┼────────────┼─────────┼──────────────┼───────────┼────────────┼──────────────┼───────────────────┼──────────┼────────────┤
│ minimum │       7514 │     903 │         2324 │       834 │         67 │          565 │                 6 │       99 │         10 │
│  median │       9029 │     982 │         2493 │       915 │         69 │          574 │                 9 │       99 │         10 │
│ maximum │      11443 │    1242 │         2768 │      1169 │         74 │          857 │                23 │       99 │         11 │
└─────────┴────────────┴─────────┴──────────────┴───────────┴────────────┴──────────────┴───────────────────┴──────────┴────────────┘
```

I believe this would need further assessment to judge whether the callback instrumentation introduces too much noise into the clock-time metrics.

**Comment by d-netto** [comment]
Latest commit should run benchmark 2*N times: N of them have the callbacks set and are used exclusively to measure cycles in GC.

This should putting the cost of a `read` syscall into the path of GC.

**Comment by vchuravy** [comment]
This is really nice! We should think about what other metrics we might want. Probably page-faults?

**Comment by d-netto** [comment]
The cycle count seems to be a bit discrepant with wall-clock-time in some of the benchmarks:

```
bench = "TimeZones.jl"
┌─────────┬────────────┬─────────┬──────────────┬───────────┬────────────┬──────────────┬───────────────────┬──────────┬────────────┐
│         │ total time │ gc time │ cycles in gc │ mark time │ sweep time │ max GC pause │ time to safepoint │ max heap │ percent gc │
│         │         ms │      ms │          1e6 │        ms │         ms │           ms │                us │       MB │          % │
├─────────┼────────────┼─────────┼──────────────┼───────────┼────────────┼──────────────┼───────────────────┼──────────┼────────────┤
│ minimum │       1825 │    1156 │           71 │      1124 │         32 │          350 │                13 │     5086 │         57 │
│  median │       1858 │    1217 │           75 │      1176 │         41 │          394 │                16 │     5086 │         59 │
│ maximum │       2125 │    1532 │          103 │      1466 │         66 │          535 │                19 │     5086 │         63 │
└─────────┴────────────┴─────────┴──────────────┴───────────┴────────────┴──────────────┴───────────────────┴──────────┴────────────┘
```

**Comment by d-netto** [comment]
Actually, I'll need to double check if GCBenchmarks measures wall-clock-time of cpu-time. Still 75 * 10^6 / (2.5 GHz) = 30ms. Not sure if wall-clock-time vs cpu-time could explain this order of magnitude difference.

**Comment by d-netto** [comment]
Indeed, replacing `PERF_TYPE_HARDWARE` with `PERF_TYPE_SOFTWARE` and `PERF_COUNT_HW_CPU_CYCLES` gives `23ms` for  median time in GC, which is consistent with the cycle measurement...

**Pull request closed without merging**
