### PR TITLE
Add benchmark and reorganize

### PR DESCRIPTION
**Pull request by kpamnany**
- Add rb_tree benchmark.
- Move benchmarks into classes: serial, multithreaded, slow.
- Switch from ArgParse to DocOpt.
- Add `--scale <maxthreads>` option.
- Remove all `Manifest.toml`s.
- Use `joinpath` instead of `/`.

### CODE REVIEW

**Comment by oscardssmith** [comment]
what's the difference between `--scale <maxthreads>` and `--threads t`?

**Comment by kpamnany** [comment]
`--scale <maxthreads>` will run the benchmark with 1, 2, 4, ..., M threads, where `M <= <maxthreads>`. `--threads <t>` just runs the benchmark with `<t>` threads.

I find ArgParse clunky in comparison to DocOpt; you can see from the code that this is much simpler and somewhat self-documenting. But it is slower. I also have no strong opinion and am willing to switch it back.

**Comment by kpamnany** [comment]
I added [this code](https://github.com/kpamnany/GCBenchmarks/blob/kp/tvbench/benches/slow/rb_tree/rb_tree.jl#L90-L94) with an explicit call to `GC.gc()` because it makes the duration of the pauses clear.

To get back to the original code by @tveldhui, uncomment [these lines](https://github.com/kpamnany/GCBenchmarks/blob/kp/tvbench/benches/slow/rb_tree/rb_tree.jl#L90-L105) and comment [these](https://github.com/kpamnany/GCBenchmarks/blob/kp/tvbench/benches/slow/rb_tree/rb_tree.jl#L106-L114).

**Comment by oscardssmith** [comment]
This seems reasonable to me. I'll merge unless there are objections.

**Comment by oscardssmith** [comment]
Can you update to reflect https://github.com/JuliaCI/GCBenchmarks/pull/28?

**Pull request merged**
