### PR TITLE
remove loop

### PR DESCRIPTION
**Pull request by oscardssmith**
now runs each benchmark in it's own process.

### CODE REVIEW

**Comment by chflood** [comment]
Before:
julia run_benchmarks.jl 3
category = "TimeZones"
test = "TimeZones.jl"
run time: 706ms min, 2335ms max 1100ms median
gc time: 0ms min, 1587ms max, 439ms median

After:
julia run_benchmarks.jl  3
category = "TimeZones"
test = "TimeZones.jl"
median time: 2.071309008
mean GC time: Any[1.384555556, 1.490022725, 1.481385896]

The before output is more informative.

**Comment by oscardssmith** [comment]
I think you may have commits that you haven't pushed. If you look at the code, I haven't changed what gets displayed.

**Comment by oscardssmith** [comment]
Oh, were you comparing to https://github.com/JuliaCI/GCBenchmarks/pull/8? If you merge that, I'll update this PR.

**Comment by oscardssmith** [comment]
@chflood I've rebased this so it has the good printing now. (Also, we should get CI on this repository so we can detect breakage)

**Pull request merged**
