### PR TITLE
Binary tree stresstest

### PR DESCRIPTION
**Pull request by Seelengrab**
As discussed on Slack! Let me know if you want this structured differently or have these two share code. I keep them seperated for now to not introduce any unnecessary variables from dispatch/inference optimizing differently or similar. I also fixed a bug in the `run_one_benchmark.jl`, where it didn't pick a default value if only the single benchmark was supplied.

Also unsure whether `@threads` should be here - I had it in my initial test/finding, but maybe it just adds unnecessary noise here.

CC: @vchuravy

### CODE REVIEW

**Comment by oscardssmith** [comment]
is this significantly different than https://github.com/JuliaCI/GCBenchmarks/blob/main/benches/linked/tree.jl?

**Comment by oscardssmith** [comment]
Can you rebase this on main? This looks good to merge, but we just updated the repo to support threads, and refactored the test runner in the process.

**Comment by oscardssmith** [comment]
Can you rebase this on main? This looks good to merge, but we just updated the repo to support threads, and refactored the test runner in the process.

**Comment by Seelengrab** [comment]
The timings with multiple threads are lower, but still exhibit the same behavior. Should still be a worthwhile benchmark, especially since (I think?) this is the only one so far that uses multiple threads as well.

**Comment by oscardssmith** [comment]
This produces really interesting numbers.
```
julia --project=. run_benchmarks.jl --bench=binary_tree/tree_mutable.jl
run time: 13188ms min, 14680ms max 13574ms median
gc time: 2843ms min, 3146ms max, 2936ms median

julia --project=. run_benchmarks.jl --bench=binary_tree/tree_mutable.jl --threads=4
run time: 8548ms min, 11813ms max 8813ms median
gc time: 4617ms min, 6103ms max, 4715ms median

julia --project=. run_benchmarks.jl --bench=binary_tree/tree_immutable.jl
run time: 6744ms min, 8653ms max 7238ms median
gc time: 1173ms min, 1461ms max, 1242ms median

julia --project=. run_benchmarks.jl --bench=binary_tree/tree_immutable.jl --threads=4
run time: 5197ms min, 6745ms max 6114ms median
gc time: 2342ms min, 3000ms max, 2843ms median
```

So `mutable` is slower, but also, `--threads=4` speeds up the program, but slows down the GC. @chflood is there an obvious reason why GC should significantly slow down when you have more GC threads? That seems un-intuitive to me. Is it memory locality?
It will be interesting to see how this changes when we get parallel GC.

**Comment by vchuravy** [comment]
We should also measure how close we get to our heap thresholds, this benchmark runs better on my machine with >> 20GB of RAM then @Seelengrab machine with ~20GB and the amout allocated was around 9GB

**Comment by Seelengrab** [comment]
Notably, the 9GiB were from the immutable case. The mutable case is a lot worse:

```julia
julia> @time New.binary_trees(devnull, 21) # immutable
 12.247241 seconds (305.93 M allocations: 9.133 GiB, 40.22% gc time, 7.51% compilation time)

# restart

julia> @time New.binary_trees(devnull, 21) # mutable
 17.923601 seconds (614.21 M allocations: 18.320 GiB, 44.72% gc time, 3.94% compilation time)
```

and my versoninfo:

```
julia> versioninfo()
Julia Version 1.9.0-DEV.468
Commit 862018b20d (2022-05-04 15:57 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

Fewer threads is always slower and while these two runs were with some additional load in the background, they still show vastly different timings.

**Comment by vchuravy** [comment]
And on my machine:

```
julia> @time BinaryTreeImmutable.binary_trees(devnull, 21)
  5.971174 seconds (305.49 M allocations: 9.104 GiB, 23.12% gc time)
```

```
julia> @time BinaryTreeMutable.binary_trees(devnull, 21)
 12.249979 seconds (613.77 M allocations: 18.292 GiB, 27.96% gc time)
```

```
julia> versioninfo()
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 16 × AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_PKG_DEVDIR = /home/vchuravy/src
```

**Review by chflood — APPROVED** [review]
This looks fine.  We might want to one day merge this with the other tree benchmark but for now I can see utility for having both.

**Pull request merged**
